//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HR.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_HRTYPE                      129
#define IDD_CONTROLBOX                  130
#define IDI_ICON1                       133
#define IDD_GRAB                        134
#define IDD_YESNO_DLG                   135
#define IDC_UP                          1000
#define IDC_LEFT                        1001
#define IDC_RIGHT                       1002
#define IDC_DOWN                        1003
#define IDC_INIT                        1004
#define IDC_STOP                        1005
#define IDC_TEST                        1011
#define IDC_COMBO1                      1013
#define IDC_ALLSTOP                     1015
#define IDC_READY                       1016
#define IDC_DEMO                        1017
#define IDC_JOYSTICK                    1018
#define IDC_RIPSYNC                     1019
#define IDC_NICEMOTION                  1019
#define IDC_TEST2                       1020
#define IDC_GRAB                        1021
#define IDC_RESETARM                    1022
#define IDC_OBJX                        1023
#define IDC_TEST3                       1023
#define IDC_OBJY                        1024
#define IDC_MOVELEFT                    1024
#define IDC_OBJZ                        1025
#define IDC_MOVERIGHT                   1025
#define IDC_HANDRST                     1026
#define IDC_TTT                         1027
#define IDC_TEST4                       1027
#define IDC_SENSOR                      1028
#define IDC_SENSOROFF                   1029
#define IDC_HANDSTP                     1029
#define IDC_WALLY                       1030
#define IDC_HANDCLS                     1031
#define IDC_WALKING                     1032
#define IDC_STOPWALK                    1033
#define IDC_IDLEENABLE                  1034
#define IDC_IDLEDISABLE                 1035
#define IDC_CLEAN                       1036
#define IDC_HANDINIT                    1037
#define IDC_NICEMOTION2                 1038
#define IDC_NICEMOTION3                 1039
#define IDC_PLAYALONE                   1040
#define IDC_READREADY                   1041
#define IDC_READING                     1042

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
