#if !defined(AFX_IMAGELIST_H__F1784906_33A5_4D5C_909B_02D31FAEA6A5__INCLUDED_)
#define AFX_IMAGELIST_H__F1784906_33A5_4D5C_909B_02D31FAEA6A5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CImageList1 wrapper class

class CImageList1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CImageList1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xfaf056d6, 0xa683, 0x11d1, { 0xbb, 0x57, 0x0, 0xc0, 0x4f, 0xcc, 0xb6, 0xbb } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetSizeX();
	void SetSizeX(long);
	long GetSizeY();
	void SetSizeY(long);
	BOOL GetBMultiSelect();
	void SetBMultiSelect(BOOL);
	long GetKeyPreSet();
	void SetKeyPreSet(long);
	long GetKeyDisable();
	void SetKeyDisable(long);
	long GetSelectedDisplay();
	void SetSelectedDisplay(long);
	BOOL GetHorizontalScroll();
	void SetHorizontalScroll(BOOL);
	long GetDecorationType();
	void SetDecorationType(long);

// Operations
public:
	long AddImage(LPCTSTR pName, const VARIANT& pImage);
	long InsertImageAt(long pos, LPCTSTR pName, const VARIANT& pImage);
	BOOL IsSelected(long pos);
	BOOL Select(long pos);
	BOOL SelectMultiple(const VARIANT& pArray);
	BOOL Deselect(long pos);
	BOOL DeselectMultiple(const VARIANT& pArray);
	void DeselectAll();
	void RemoveAll();
	BOOL DeleteAt(long pos);
	void DeleteMultiple(const VARIANT& pArray);
	void Reorder(const VARIANT& pArray);
	CString GetName(long pos);
	void DeleteSelected();
	long AddBlankImage(LPCTSTR pName);
	void SetImageAt(long Nth, const VARIANT& pDib);
	long InsertBlankImageAt(long Nth, LPCTSTR pName);
	long GetNumSelected();
	void ScrollToNthImage(long Nth);
	long GetNumItems();
	long GetNthSelected(long Nth);
	long AddImagePtr(LPCTSTR pName, long pDib);
	long InsertImageAtPtr(long pos, LPCTSTR pName, long pDib);
	void SetImageAtPtr(long pos, long pDib);
	void SetDefaultTextColor(long color);
	long GetDefaultTextColor();
	long SortByText(BOOL bDecending);
	long SortByColor(BOOL bDecending);
	void SetTextColor(long pos, long color);
	void Swap(long i, long j);
	void ReorderPtr(long pOrder);
	void Reserve(long nSize);
	void SetNamedImageAtPtr(long Nth, LPCTSTR pName, long pDib);
	void SetNameAt(long pos, LPCTSTR pName);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IMAGELIST_H__F1784906_33A5_4D5C_909B_02D31FAEA6A5__INCLUDED_)
